export const stylesHomeWhite = {
    container: {
        width:"100%",
        height:"100%",
        backgroundColor: '#fff',
        overflow:'scroll'
      },
      text:{
        textAlign:"center",
        width:380,
        marginTop:24,
        marginLeft:10,
        color:"#1c1c1c",
        fontSize:14,
        fontWeight:400,
      },
      input:{
        width:368,
        height:40,
        borderRadius:10,
        marginLeft:10,
        marginTop:24,
        borderWidth:2,
        borderColor:"#bbbbbb",
        color:"#1c1c1c",
      },
      name:{
        marginTop:64,
        marginLeft:"22.5%",
      },
      icon:{
        marginTop:-31.75,
        marginLeft:347.75,
        fill:'#231f20'
      },
      tab:{
        color:"#1c1c1c",
        width:600,
        fontSize:24,
        marginTop:34,
        marginLeft:10
      },
      categories:{
        width:393,
        height:250,
        display:"flex",
        flexDirection:"column",
        flexWrap:"wrap",
        alignContent:"space-around",
        justifyContent:"space-between",
        marginTop:18,
      },
      title:{
        fontWeight:400,
        fontSize:14,
        color:"#1c1c1c",
        marginTop:15,
        marginLeft:16
      },
      category:{
            width:176,
            height:48,
            borderRadius:10,
            borderWidth:2,
            borderColor:"#bbbbbb",
      },
      warning:{
        width:368,
        marginTop:34,
        marginLeft:10,
        fontWeight:400,
        fontSize:14,
        color:"#555555",
        marginEnd:300,
      },
      homeButton:{
        marginEnd:12,
        marginLeft:10
      },
      footer:{
        position:'absolute',
        left:0,
        right:0,
        bottom:10,
        width:"100%",
        flexDirection:'row'
      },
      subject:{
        marginLeft:8,
        marginEnd:12
      },
      favorites:{
        height:48,
        width:112,
        borderRadius:10,
        justifyContent:'center',
        backgroundColor:"#fff",
        marginLeft:125,
        marginEnd:12,
        alignItems:"center",
        borderWidth:2,
        borderColor:"##FF7A00"
      },
      price:{
        color:"#1c1c1c",
        fontWeight:600,
        fontSize:14
      },
      quantity:{
        color:'#1c1c1c',
        fontWeight:400,
        fontSize:10
      },
}