export const stylesHomeBlack = {
    container: {
        width:"100%",
        height:"100%",
        backgroundColor: '#151515',
        overflow:'scroll'
      },
      text:{
        textAlign:"center",
        width:380,
        marginTop:24,
        marginLeft:10,
        color:"#ffffff",
        fontSize:14,
        fontWeight:400,
      },
      input:{
        width:368,
        height:40,
        backgroundColor: "#555555",
        borderRadius:10,
        marginLeft:10,
        marginTop:24,
        color:"#fff",
        borderWidth:2,
        borderColor:"#000000",
      },
      name:{
        marginTop:64,
        marginLeft:"22.5%",
      },
      icon:{
        marginTop:-31.75,
        marginLeft:347.75,
      },
      tab:{
        color:"#fff",
        width:600,
        fontSize:24,
        marginTop:34,
        marginLeft:10
      },
      categories:{
        width:393,
        height:250,
        display:"flex",
        flexDirection:"column",
        flexWrap:"wrap",
        alignContent:"space-around",
        justifyContent:"space-between",
        marginTop:18,
      },
      title:{
        fontWeight:400,
        fontSize:14,
        color:"#fff",
        marginTop:15,
        marginLeft:16
      },
      category:{
            width:176,
            height:48,
            backgroundColor:"#222222",
            borderRadius:10,
            borderWidth:2,
            borderColor:"#555555",
      },
      warning:{
        width:368,
        marginTop:34,
        marginLeft:10,
        fontWeight:400,
        fontSize:14,
        color:"#bbb",
        marginEnd:300,
      },
      homeButton:{
        marginEnd:12,
        marginLeft:10
      },
      footer:{
        position:'absolute',
        left:0,
        right:0,
        bottom:10,
        width:"100%",
        flexDirection:'row'
      },
      subject:{
        marginLeft:8,
        marginEnd:12
      },
      favorites:{
        height:48,
        width:112,
        backgroundColor:'#555555',
        borderRadius:10,
        justifyContent:'center',
        borderWidth:2,
        borderColor:"#FF7A00",
        marginLeft:125,
        marginEnd:12,
        alignItems:"center"
      },
      price:{
        color:"#fff",
        fontWeight:600,
        fontSize:14
      },
      quantity:{
        color:'#fff',
        fontWeight:400,
        fontSize:10
      }
}