export const stylesBasketWhite = {
    container:{
        width:393,
        height:'100%',
        backgroundColor:'#fff',
        overflow:'scroll'
    },
    name:{
        marginTop:64,
        marginLeft:"22.5%",
      },
      text:{
        textAlign:"center",
        width:380,
        marginTop:24,
        marginLeft:10,
        color:"#1c1c1c",
        fontSize:14,
        fontWeight:400,
      },
      input:{
        width:368,
        height:40,
        borderRadius:10,
        marginLeft:10,
        marginTop:24,
        borderWidth:2,
        borderColor:"#bbbbbb",
        color:"#1c1c1c",
      },
      icon:{
        marginTop:-31.75,
        marginLeft:347.75,
      },
      footer:{
        position:'absolute',
        left:0,
        right:0,
        bottom:10,
        width:"100%",
        flexDirection:'row'
      },
      homeButton:{
        marginEnd:12,
        marginLeft:10
      },
      subject:{
        marginLeft:8,
        marginEnd:12
      },
      favorites:{
        height:48,
        width:112,
        borderRadius:10,
        justifyContent:'center',
        backgroundColor:"#fff",
        marginLeft:125,
        marginEnd:12,
        alignItems:"center",
        borderWidth:2,
        borderColor:"##FF7A00"
      },
      price:{
        color:"#1c1c1c",
        fontWeight:600,
        fontSize:14
      },
      quantity:{
        color:'#1c1c1c',
        fontWeight:400,
        fontSize:10
      },
      tab:{
        color:"#1c1c1c",
        width:600,
        fontSize:24,
        marginTop:34,
        marginLeft:10
      },
      sum:{
        color:"#1c1c1c",
        fontWeight:400,
        fontSize:16,
        marginLeft:10
      },
      card:{
        width:368,
        height:118,
        backgroundColor:"#fff",
        borderRadius:10,
        borderWidth:2,
        borderColor:"#bbb",
        marginTop:12,
        marginLeft:10
      },
      title:{
        width:336,
        fontWeight:400,
        fontSize:14,
        color:"#1c1c1c",
        marginTop:16,
        marginLeft:16,
      },
      button:{
        borderRadius:10,
        height:40,
        width:114,
        color:"#1c1c1c", 
        backgroundColor:"#eee",
        display:"flex", 
        alignItems:"center",
        flexDirection:"row",
        justifyContent:"space-around", 
        margin:16
      },
      minus:{
        fontWeight:400,
        fontSize:20,
        color:"#1c1c1c",
        marginRight:10
      },
      plus:{
        fontWeight:400,
        fontSize:20,
        color:"#1c1c1c",
        marginLeft: 10
      },
      cost:{
        color:"#1c1c1c",
        fontWeight:400,
        fontSize:16,
      },
      amount:{
        backgroundColor:"#fff",
        justifyContent:'center',
        alignItems:"center",
        borderRadius:10,
        borderWidth:2,
        borderColor:"#ff7a00",
        width:38,
        height:40,
        marginLeft:167,
        marginTop:-56,
        marginEnd:16
      },
      amountText:{
        fontWeight:600,
        fontSize:16,
        color:"#1c1c1c"
      },
      call:{
        width:210,
        height:48,
        borderRadius:10,
        borderWidth:2,
        borderColor:"#ff7a00",
        marginTop:24,
        marginLeft:10,
        justifyContent:'center',
        alignItems:"center",
        backgroundColor:"#fff",
      },
      callText:{
        fontWeight:800,
        fontSize:14,
        color:"#1c1c1c"
      },
      image:{
        position:"absolute",
        width:140,
        height:140,
        marginLeft:224,
  
        borderBottomRightRadius:10,
        borderTopRightRadius:10,
      },
      description:{
        color:"#1c1c1c",
        fontWeight:400,
        fontSize:14,
        marginLeft:16,
        marginTop:16,
      },
      line:{
        marginTop:32
      },
      preOrderText:{
        width:368,
        marginTop:8,
        marginLeft:10,
        color:'#1c1c1c'
      },
      form:{
        width:368,
        height:218,
        marginTop:16,
        marginLeft:10,
        display:"flex",
        flexDirection:"column",
        flexWrap:"wrap",
        alignContent:"space-around",
        justifyContent:"space-between",
        alignItems:'center'
      },
      info:{
        width:176,
        height:67
      },
      infoText:{
        fontWeight:400,
        fontSize:14,
        color:"#1c1c1c"
      },
      infoInput:{
        width:176,
        marginTop:2,
        height:48,
        borderRadius:10,
        borderWidth:2,
        borderColor:"#bbb",
        backgroundColor:"#fff",
      },
      submit:{
        height:48,
        width:176,
        backgroundColor:"#fff",
        borderRadius:10,
        borderWidth:2,
        borderColor:"#ff7a00",
        display:"flex",
        alignItems:"center",
        justifyContent:"center"
      },
      submitText:{
        color:"#1c1c1c",
        fontWeight:600,
        fontSize:14,
      }
}