export const stylesSaladsBlack = {
    container: {
        width:"100%",
        height:"100%",
        backgroundColor: '#151515',
        overflow:'scroll'
      },
      text:{
        textAlign:"center",
        width:380,
        marginTop:24,
        marginLeft:10,
        color:"#ffffff",
        fontSize:14,
        fontWeight:400,
      },
      input:{
        width:368,
        height:40,
        backgroundColor: "#555555",
        borderRadius:10,
        marginLeft:10,
        marginTop:24, 
        color:"#fff",
        borderWidth:2,
        borderColor:"#000000"
      },
      name:{
        marginTop:64,
        marginLeft:"22.5%",
      },
      icon:{
        marginTop:-31.75,
        marginLeft:347.75,
      },
      tab:{
        color:"#fff",
        width:600,
        fontSize:24,
        marginTop:34,
        marginLeft:10
      },
      card:{
        width:368,
        marginTop:18,
        marginLeft: 10,
        backgroundColor:"#222222",
        borderRadius:10,
        borderWidth:2,
        borderColor:"#555555",
        height:118
      },
      title:{
        fontWeight:600,
        fontSize:14,
        color:"#fff",
        marginTop:16,
        marginLeft:16
      },
      minus:{
        fontWeight:400,
        fontSize:20,
        color:"#fff",
        marginRight:10
      },
      plus:{
        fontWeight:400,
        fontSize:20,
        color:"#fff",
        marginLeft: 10
      },
      footer:{
        position:'absolute',
        left:0,
        right:0,
        bottom:10,
        width:"100%",
        flexDirection:'row'
      },
      homeButton:{
        marginEnd:12,
        marginLeft:10
      },
      subject:{
        marginLeft:8,
        marginEnd:12
      },
      favorites:{
        height:48,
        width:112,
        backgroundColor:'#555555',
        borderRadius:10,
        justifyContent:'center',
        marginLeft:125,
        marginEnd:12,
        alignItems:"center",
        borderWidth:2,
        borderColor:"#ff7a00"
      },
      price:{
        color:"#fff",
        fontWeight:600,
        fontSize:14
      },
      quantity:{
        color:'#fff',
        fontWeight:400,
        fontSize:10
      },
      button:{
        height:40,
        width:114,
        borderRadius:10,
        color:"#fff", 
        backgroundColor: "#555555",
        display:"flex", 
        alignItems:"center",
        flexDirection:"row",
        justifyContent:"space-around", 
        margin:16, 
      },
      cost:{
        color:"#fff",
        fontWeight:400,
        fontSize:16,
      },
      amount:{
        backgroundColor:"#555555",
        justifyContent:'center',
        alignItems:"center",
        borderRadius:10,
        borderWidth:2,
        borderColor:"#ff7a00",
        width:38,
        height:40,
        marginLeft:167,
        marginTop:-56,
        marginEnd:16
      },
      amountText:{
        fontWeight:600,
        fontSize:16,
        color:"#fff"
      }, 
      image:{
        position:'absolute',
          width:140,
          height:140,
          marginLeft:224,
          borderBottomRightRadius:10,
          borderTopRightRadius:10,
      },
    
    description:{
      color:"#fff",
      fontWeight:400,
      fontSize:14,
      marginLeft:16,
      marginTop:16,
    }
}